import AutoGraphRoundedIcon from '@mui/icons-material/AutoGraphRounded'
import { Alert, Box, Card, CardContent, Chip, MenuItem, Skeleton, Stack, TextField, ToggleButton, ToggleButtonGroup, Typography } from '@mui/material'
import { Bar, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { EmptyState, ErrorState } from '../../../components/States'
import { MarkdownText } from '../../../components/MarkdownText'
import { useDevelopmentViewModel, type DevelopmentSeason } from '../../../features/analytics/useAnalyticsViewModels'
import { formatChartValue, formatDistance, formatDuration, formatSpeedMps } from '../../../utils/format'
import { AnalyticsHeader, ChartPanel, Metric, SectionHeading, tooltipStyle } from './AnalyticsUi'

const seasonLabels: Record<DevelopmentSeason, string> = { year: 'Ganzes Jahr', spring: 'Frühling', summer: 'Sommer', autumn: 'Herbst', winter: 'Winter' }
function numberValue(source: Record<string, unknown> | undefined, key: string) { const value = source?.[key]; return typeof value === 'number' && Number.isFinite(value) ? value : null }
function monthLabel(value: string) { return new Intl.DateTimeFormat('de-DE', { month: 'short', year: '2-digit' }).format(new Date(`${value}T12:00:00`)) }
function trendLabel(status: string) { return ({ insufficient_data: 'Noch zu wenig Daten', positive: 'Positiver Trend', negative: 'Unter Vergleichsniveau', stable: 'Stabiler Trend' } as Record<string, string>)[status] ?? status }

export function MinimalDevelopmentPage() {
  const vm = useDevelopmentViewModel()
  const data = vm.insights.data
  const current = data?.current
  const monthly = (data?.monthly ?? []).map((point) => ({ ...point, label: monthLabel(point.period_start), distanceKm: point.distance_m / 1000, speedKmh: point.avg_speed_mps == null ? null : point.avg_speed_mps * 3.6 }))
  return <Stack spacing={{ xs: 6, md: 8 }}>
    <AnalyticsHeader eyebrow="Langfristige Entwicklung" title="Fortschritt braucht Kontext." description="Avento stellt Trainingsumfang, Belastung und Tempo der passenden Vorperiode gegenüber und benennt nur Muster, die deine vorhandenen Daten tragen." />
    <Card component="section" aria-label="Entwicklungszeitraum" sx={{ bgcolor: 'var(--avento-minimal-surface-raised)' }}><CardContent sx={{ p: { xs: 2.5, md: 3.5 } }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ xs: 'stretch', sm: 'center' }} gap={2}><Box><Typography variant="h3">Langfristiger Zeitraum</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Monatliche Entwicklung bis heute</Typography></Box><ToggleButtonGroup exclusive value={vm.years} onChange={(_, value: number | null) => value && vm.update({ years: value })} aria-label="Jahre auswählen">{[1, 3, 5].map((value) => <ToggleButton value={value} key={value}>{value} {value === 1 ? 'Jahr' : 'Jahre'}</ToggleButton>)}</ToggleButtonGroup></Stack></CardContent></Card>
    {vm.insights.isLoading && <Stack spacing={2}><Skeleton variant="rounded" height={160} /><Skeleton variant="rounded" height={400} /></Stack>}
    {vm.insights.isError && <ErrorState error={vm.insights.error} onRetry={() => void vm.insights.refetch()} />}
    {data && <>
      <Box component="section" aria-labelledby="development-scope"><SectionHeading id="development-scope" eyebrow="Umfang & Belastung" title={numberValue(current, 'activity_count') ? 'Dein Training im zeitlichen Vergleich.' : 'Noch keine belastbare Entwicklung.'} description={`Verglichen wird mit ${new Intl.DateTimeFormat('de-DE').format(new Date(`${data.previous_period.date_from}T12:00:00`))} bis ${new Intl.DateTimeFormat('de-DE').format(new Date(`${data.previous_period.date_to}T12:00:00`))}.`} /><Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2,minmax(0,1fr))', md: 'repeat(4,minmax(0,1fr))' }, gap: { xs: 2, md: 4 }, mt: 4 }}><Metric label="Distanz" value={formatDistance(numberValue(current, 'distance_m'))} change={data.changes.distance_m} hint="zur Vorperiode" /><Metric label="Bewegungszeit" value={formatDuration(numberValue(current, 'moving_time_s'))} change={data.changes.moving_time_s} hint="zur Vorperiode" /><Metric label="Trainingsbelastung" value={(numberValue(current, 'training_load') ?? 0).toLocaleString('de-DE', { maximumFractionDigits: 0 })} change={data.changes.training_load} hint="zur Vorperiode" /><Metric label="Ø Geschwindigkeit" value={formatSpeedMps(numberValue(current, 'avg_speed_mps'))} change={data.changes.avg_speed_mps} hint="zur Vorperiode" /></Box></Box>
      {monthly.length ? <ChartPanel title="Trainingsverlauf" description="Distanz, Belastung und Tempo pro Monat; Tempo ist gestrichelt dargestellt und nicht nur farblich unterscheidbar." summary={`${monthly.length} Monatswerte im Zeitraum. ${data.fitness_trend.statement}`}><ResponsiveContainer width="100%" height={350}><ComposedChart data={monthly} margin={{ top: 10, right: 8, left: -8, bottom: 0 }}><CartesianGrid vertical={false} stroke="rgba(255,255,255,.1)" strokeDasharray="4 4" /><XAxis dataKey="label" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis yAxisId="distance" width={45} unit=" km" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis yAxisId="speed" orientation="right" width={52} unit=" km/h" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} formatter={(value, name) => [formatChartValue(value, 1), name]} /><Legend /><Bar yAxisId="distance" dataKey="distanceKm" name="Distanz (km)" fill="#65c8c1" radius={[5, 5, 0, 0]} isAnimationActive={false} /><Line yAxisId="speed" dataKey="speedKmh" name="Ø Geschwindigkeit" stroke="#e1b25d" strokeWidth={2.5} strokeDasharray="7 4" dot={false} connectNulls isAnimationActive={false} /></ComposedChart></ResponsiveContainer></ChartPanel> : <EmptyState title="Noch kein Verlauf" description="Für diesen Zeitraum liegen keine monatlichen Aggregate vor." />}
      <Card component="section" aria-labelledby="fitness-trend" sx={{ bgcolor: 'var(--avento-minimal-surface-raised)' }}><CardContent sx={{ p: { xs: 3, md: 4 } }}><Stack direction={{ xs: 'column', md: 'row' }} gap={3} justifyContent="space-between"><Box><Typography variant="overline" color="primary.main">Fitnesstrend</Typography><Typography id="fitness-trend" variant="h2" sx={{ mt: 1 }}>{trendLabel(data.fitness_trend.status)}</Typography><Typography color="text.secondary" sx={{ mt: 1.5, maxWidth: 720 }}>{data.fitness_trend.statement}</Typography></Box><AutoGraphRoundedIcon color="primary" sx={{ fontSize: 42 }} /></Stack><Stack direction="row" gap={1} flexWrap="wrap" sx={{ mt: 3 }}><Chip label={`Konfidenz: ${data.fitness_trend.confidence}`} /><Chip variant="outlined" label={`${data.fitness_trend.sample_size} Aktivitäten`} />{data.fitness_trend.speed_change_percent != null && <Chip variant="outlined" label={`Tempo ${data.fitness_trend.speed_change_percent >= 0 ? 'gestiegen' : 'gesunken'}: ${Math.abs(data.fitness_trend.speed_change_percent).toLocaleString('de-DE', { maximumFractionDigits: 1 })} %`} />}</Stack></CardContent></Card>
      <Box component="section" aria-labelledby="patterns"><SectionHeading id="patterns" eyebrow="Erkannte Muster" title="Beobachtungen mit offengelegter Grundlage." />{data.patterns.length ? <Stack spacing={1} sx={{ mt: 3 }}>{data.patterns.map((pattern, index) => <Box key={`${pattern.kind}-${index}`} sx={{ py: 2.5, borderTop: '1px solid', borderColor: 'divider' }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={1}><Typography variant="h3">{pattern.statement}</Typography><Chip size="small" label={pattern.confidence} sx={{ alignSelf: 'flex-start' }} /></Stack><Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>{pattern.sample_size} Aktivitäten · {pattern.method}</Typography></Box>)}</Stack> : <Typography color="text.secondary" sx={{ mt: 2 }}>Noch keine belastbaren Muster. Avento wartet auf eine ausreichende Datengrundlage.</Typography>}</Box>
      <Alert severity="info">{data.disclaimer}</Alert>
    </>}
    <Card component="section" aria-labelledby="review-title" sx={{ bgcolor: 'var(--avento-minimal-surface-subtle)' }}><CardContent sx={{ p: { xs: 2.5, md: 4 } }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={2}><Box><Typography id="review-title" variant="h2">Saison- & Jahresrückblick</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Eine Zusammenfassung ausschließlich auf Basis deiner gespeicherten Aktivitäten.</Typography></Box><Stack direction={{ xs: 'column', sm: 'row' }} gap={1}><TextField select label="Jahr" value={vm.reviewYear} onChange={(event) => vm.update({ reviewYear: Number(event.target.value) })}>{Array.from({ length: 10 }, (_, index) => vm.currentYear - index).map((year) => <MenuItem value={year} key={year}>{year}</MenuItem>)}</TextField><TextField select label="Zeitraum" value={vm.season} onChange={(event) => vm.update({ season: event.target.value as DevelopmentSeason })}>{Object.entries(seasonLabels).map(([value, label]) => <MenuItem value={value} key={value}>{label}</MenuItem>)}</TextField></Stack></Stack>{vm.review.isLoading && <Skeleton variant="rounded" height={180} sx={{ mt: 3 }} />}{vm.review.isError && <Box sx={{ mt: 3 }}><ErrorState error={vm.review.error} onRetry={() => void vm.review.refetch()} /></Box>}{vm.review.data && <Box sx={{ mt: 3 }}><MarkdownText content={vm.review.data.summary} /><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 2 }}>Anbieter: {vm.review.data.provider} · {seasonLabels[vm.season]} {vm.review.data.year}</Typography></Box>}</CardContent></Card>
  </Stack>
}
