import { useState } from 'react'
import ArrowForwardRoundedIcon from '@mui/icons-material/ArrowForwardRounded'
import ShareRoundedIcon from '@mui/icons-material/ShareRounded'
import { Box, Button, Card, CardContent, Chip, IconButton, Skeleton, Stack, Tooltip, Typography } from '@mui/material'
import { Link as RouterLink } from 'react-router-dom'
import type { ActivityRecord, DistanceRecord } from '../../../api'
import { EmptyState, ErrorState } from '../../../components/States'
import { useRecordsViewModel } from '../../../features/analytics/useAnalyticsViewModels'
import { AchievementShareDialog } from '../../../share/AchievementShareDialog'
import type { AchievementInfo } from '../../../share/types'
import { formatDate, formatDistance, formatDuration, formatElevation, formatSpeedMps } from '../../../utils/format'
import { AnalyticsHeader, SectionHeading } from './AnalyticsUi'

const methodLabels: Record<string, string> = { distance_record_track_points: 'Trackbasierte Abschnittszeit', distance_record_fallback: 'Gekennzeichnete Schätzung' }

export function MinimalRecordsPage() {
  const records = useRecordsViewModel()
  const [share, setShare] = useState<{ activityId: string; achievement: AchievementInfo } | null>(null)
  const data = records.data
  const hasRecords = Boolean(data && (data.longest_ride || data.highest_average_speed || data.highest_elevation_gain || data.distance_records.length))
  return <Stack spacing={{ xs: 6, md: 8 }}>
    <AnalyticsHeader eyebrow="Persönliche Bestleistungen" title="Deine stärksten Momente." description="Rekorde sind nach Gesamtleistung, Höhenmetern und Distanz geordnet. Jeder Wert führt zurück zu der Aktivität, auf der er beruht." />
    {records.isLoading && <Stack spacing={2}><Skeleton variant="rounded" height={250} /><Skeleton variant="rounded" height={350} /></Stack>}
    {records.isError && <ErrorState error={records.error} onRetry={() => void records.refetch()} />}
    {data && !hasRecords && <EmptyState title="Deine erste Bestleistung wartet" description="Mit deiner ersten passenden Aktivität beginnt hier eine persönliche Rekordgeschichte – ohne erfundene Vergleichswerte." />}
    {data && hasRecords && <>
      <Box component="section" aria-labelledby="overall-records"><SectionHeading id="overall-records" eyebrow="Gesamtleistungen" title="Die Fahrten, die herausragen." /><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3,minmax(0,1fr))' }, gap: 1.5, mt: 3 }}><RecordCard label="Längste Aktivität" record={data.longest_ride} value={data.longest_ride ? formatDistance(data.longest_ride.distance_m) : '–'} detail={data.longest_ride ? formatDuration(data.longest_ride.moving_time_s) : undefined} onShare={data.longest_ride ? () => setShare({ activityId: data.longest_ride!.activity_id, achievement: { kind: 'longest_ride', label: 'Längste Tour', value: formatDistance(data.longest_ride!.distance_m), detail: formatDuration(data.longest_ride!.moving_time_s) } }) : undefined} /><RecordCard label="Höchstes Durchschnittstempo" record={data.highest_average_speed} value={data.highest_average_speed ? formatSpeedMps(data.highest_average_speed.avg_speed_mps) : '–'} detail={data.highest_average_speed ? formatDistance(data.highest_average_speed.distance_m) : undefined} onShare={data.highest_average_speed ? () => setShare({ activityId: data.highest_average_speed!.activity_id, achievement: { kind: 'fastest_ride', label: 'Schnellste Tour', value: formatSpeedMps(data.highest_average_speed!.avg_speed_mps), detail: formatDistance(data.highest_average_speed!.distance_m) } }) : undefined} /><RecordCard label="Meiste Höhenmeter" record={data.highest_elevation_gain} value={data.highest_elevation_gain ? formatElevation(data.highest_elevation_gain.elevation_gain_m) : '–'} detail={data.highest_elevation_gain ? formatDistance(data.highest_elevation_gain.distance_m) : undefined} onShare={data.highest_elevation_gain ? () => setShare({ activityId: data.highest_elevation_gain!.activity_id, achievement: { kind: 'elevation_record', label: 'Höhenmeter-Rekord', value: formatElevation(data.highest_elevation_gain!.elevation_gain_m), detail: formatDistance(data.highest_elevation_gain!.distance_m) } }) : undefined} /></Box></Box>
      <Box component="section" aria-labelledby="distance-records"><SectionHeading id="distance-records" eyebrow="Distanzbestzeiten" title="Die schnellsten zusammenhängenden Abschnitte." description="Schätzungen sind sichtbar gekennzeichnet. Avento ergänzt keinen vorherigen Bestwert, solange die API keinen liefert." />{data.distance_records.length ? <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2,minmax(0,1fr))', xl: 'repeat(3,minmax(0,1fr))' }, gap: 1.5, mt: 3 }}>{data.distance_records.map((record) => <DistanceCard key={record.target_distance_m} record={record} onShare={() => setShare({ activityId: record.activity_id, achievement: { kind: 'distance_pr', label: `Bestzeit über ${record.target_distance_m / 1000} km`, value: formatDuration(record.duration_s), detail: formatSpeedMps(record.avg_speed_mps), segmentStartM: record.segment_start_m, segmentEndM: record.segment_end_m } })} />)}</Box> : <Typography color="text.secondary" sx={{ mt: 2 }}>Sobald eine Aktivität mindestens zehn Kilometer enthält, erscheint hier die erste Distanzbestzeit.</Typography>}</Box>
      {data.methods.length > 0 && <Box component="section" aria-labelledby="methods"><SectionHeading id="methods" eyebrow="Transparenz" title="So werden die Rekorde ermittelt." /><Stack spacing={1} sx={{ mt: 3 }}>{data.methods.map((method, index) => <Box key={`${method.name}-${index}`} sx={{ py: 2, borderTop: '1px solid', borderColor: 'divider' }}><Typography fontWeight={750}>{methodLabels[method.name] ?? method.name}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>{method.description}</Typography></Box>)}</Stack></Box>}
    </>}
    <AchievementShareDialog open={Boolean(share)} onClose={() => setShare(null)} activityId={share?.activityId ?? null} achievement={share?.achievement ?? null} />
  </Stack>
}

function RecordCard({ label, record, value, detail, onShare }: { label: string; record: ActivityRecord | null; value: string; detail?: string; onShare?: () => void }) {
  return <Card sx={{ bgcolor: 'var(--avento-minimal-surface-raised)' }}><CardContent sx={{ p: 3, height: '100%', display: 'flex', flexDirection: 'column' }}><Stack direction="row" justifyContent="space-between" gap={1}><Typography variant="overline" color="primary.main">{label}</Typography>{onShare && <Tooltip title={`${label} teilen`}><IconButton aria-label={`${label} teilen`} onClick={onShare} size="small"><ShareRoundedIcon fontSize="small" /></IconButton></Tooltip>}</Stack><Typography sx={{ fontSize: 'clamp(2.3rem,6vw,3.8rem)', lineHeight: 1, fontWeight: 660, letterSpacing: '-.05em', mt: 2 }}>{value}</Typography>{detail && <Typography color="text.secondary" sx={{ mt: 1 }}>{detail}</Typography>}{record ? <Box sx={{ mt: 'auto', pt: 4 }}><Typography variant="h4" sx={{ overflowWrap: 'anywhere' }}>{record.title}</Typography><Typography variant="caption" color="text.secondary">{formatDate(record.started_at)}</Typography><Button component={RouterLink} to={`/aktivitaeten/${record.activity_id}`} endIcon={<ArrowForwardRoundedIcon />} sx={{ display: 'flex', px: 0, mt: 1 }}>Aktivität öffnen</Button></Box> : <Typography color="text.secondary" sx={{ mt: 3 }}>Noch keine passende Aktivität.</Typography>}</CardContent></Card>
}

function DistanceCard({ record, onShare }: { record: DistanceRecord; onShare: () => void }) {
  const km = record.target_distance_m / 1000
  return <Card sx={{ bgcolor: 'var(--avento-minimal-surface-subtle)' }}><CardContent sx={{ p: 3 }}><Stack direction="row" justifyContent="space-between" alignItems="flex-start" gap={1}><Box><Typography variant="overline" color="primary.main">{km.toLocaleString('de-DE')} Kilometer</Typography><Typography variant="h2" sx={{ mt: 1 }}>{formatDuration(record.duration_s)}</Typography></Box><Tooltip title={`${km} Kilometer Bestzeit teilen`}><IconButton aria-label={`${km} Kilometer Bestzeit teilen`} onClick={onShare}><ShareRoundedIcon /></IconButton></Tooltip></Stack><Typography color="text.secondary" sx={{ mt: 1 }}>{formatSpeedMps(record.avg_speed_mps)} im Durchschnitt</Typography><Stack direction="row" gap={1} flexWrap="wrap" sx={{ mt: 2 }}>{record.estimated && <Chip size="small" variant="outlined" label="Geschätzter Wert" />}<Chip size="small" variant="outlined" label={record.source} /></Stack><Typography variant="h4" sx={{ mt: 3, overflowWrap: 'anywhere' }}>{record.title}</Typography><Typography variant="caption" color="text.secondary">{formatDate(record.started_at)}</Typography><Button component={RouterLink} to={`/aktivitaeten/${record.activity_id}`} endIcon={<ArrowForwardRoundedIcon />} sx={{ display: 'flex', px: 0, mt: 1 }}>Aktivität öffnen</Button></CardContent></Card>
}
