import { useMemo, useState } from 'react'
import CheckRoundedIcon from '@mui/icons-material/CheckRounded'
import CompareArrowsRoundedIcon from '@mui/icons-material/CompareArrowsRounded'
import { Alert, Box, ButtonBase, Card, CardContent, Chip, Skeleton, Stack, ToggleButton, ToggleButtonGroup, Typography } from '@mui/material'
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { ActivityComparisonMetric } from '../../../api'
import { EmptyState, ErrorState } from '../../../components/States'
import { MarkdownText } from '../../../components/MarkdownText'
import { useComparisonViewModel } from '../../../features/analytics/useAnalyticsViewModels'
import { formatChartValue, formatDate, formatDistance, formatDuration, formatElevation, formatHeartRate, formatSpeedMps } from '../../../utils/format'
import { AnalyticsHeader, ChartPanel, SectionHeading, tooltipStyle } from './AnalyticsUi'

type ProfileMetric = 'elevation_m' | 'speed_kmh' | 'heart_rate_bpm'
const profileMetricConfig: Record<ProfileMetric, { label: string; unit: string }> = { elevation_m: { label: 'Höhe', unit: 'm' }, speed_kmh: { label: 'Tempo', unit: 'km/h' }, heart_rate_bpm: { label: 'Puls', unit: 'bpm' } }
const colors = ['#65c8c1', '#e77b73', '#78a7e3', '#e1b25d']
const dash = ['', '8 4', '3 4', '12 4 3 4']
function efficiency(value: number | null) { return value == null ? '–' : `${value.toLocaleString('de-DE', { maximumFractionDigits: 3 })} km/h je bpm` }
function wind(value: number | null) { if (value == null) return '–'; if (Math.abs(value) < .5) return 'nahezu neutral'; return `${Math.abs(value).toLocaleString('de-DE', { maximumFractionDigits: 1 })} km/h ${value > 0 ? 'Gegenwind' : 'Rückenwind'}` }
function score(value: number | null) { return value == null ? '–' : `${value.toLocaleString('de-DE', { maximumFractionDigits: 0 })} Punkte` }

export function MinimalComparePage() {
  const vm = useComparisonViewModel()
  const [profileMetric, setProfileMetric] = useState<ProfileMetric>('elevation_m')
  const result = vm.compare.data?.activities ?? []
  const metrics: ActivityComparisonMetric[] = vm.compare.data?.metrics?.length ? vm.compare.data.metrics : result.map((activity) => ({ activity_id: activity.id, title: activity.title, distance_m: activity.distance_m, duration_s: activity.duration_s, moving_time_s: activity.moving_time_s, elevation_gain_m: activity.elevation_gain_m, avg_speed_mps: activity.avg_speed_mps, avg_hr_bpm: activity.avg_hr_bpm, max_hr_bpm: activity.max_hr_bpm, efficiency_kmh_per_bpm: activity.avg_speed_mps != null && activity.avg_hr_bpm ? activity.avg_speed_mps * 3.6 / activity.avg_hr_bpm : null, headwind_kmh: null, relative_score: null }))
  const profiles = vm.compare.data?.profiles ?? []
  const profileData = useMemo(() => { const rows = new Map<number, Record<string, number | null>>(); profiles.forEach((profile, index) => profile.points.forEach((point) => { const progress = Math.round(point.progress_percent * 10) / 10; const row = rows.get(progress) ?? { progress }; row[`activity_${index}`] = point[profileMetric]; rows.set(progress, row) })); return [...rows.values()].sort((a, b) => Number(a.progress) - Number(b.progress)) }, [profiles, profileMetric])
  const leaders = {
    speed: [...metrics].filter((item) => item.avg_speed_mps != null).sort((a, b) => (b.avg_speed_mps ?? 0) - (a.avg_speed_mps ?? 0))[0],
    efficiency: [...metrics].filter((item) => item.efficiency_kmh_per_bpm != null).sort((a, b) => (b.efficiency_kmh_per_bpm ?? 0) - (a.efficiency_kmh_per_bpm ?? 0))[0],
    score: [...metrics].filter((item) => item.relative_score != null).sort((a, b) => (b.relative_score ?? 0) - (a.relative_score ?? 0))[0],
  }
  return <Stack spacing={{ xs: 6, md: 8 }}>
    <AnalyticsHeader eyebrow="Aktivitäten vergleichen" title="Unterschiede auf einen Blick." description="Wähle zwei bis vier Aktivitäten. Avento verwendet für jede Kennzahl dieselbe Skala und kennzeichnet Reihen zusätzlich mit Namen und Linienmustern." />
    {vm.list.isLoading && <Skeleton variant="rounded" height={360} />}
    {vm.list.isError && <ErrorState error={vm.list.error} onRetry={() => void vm.list.refetch()} />}
    {vm.list.data?.items.length === 0 && <EmptyState title="Keine Fahrten zum Vergleichen" description="Für einen Vergleich werden mindestens zwei gespeicherte Aktivitäten benötigt." />}
    {vm.list.data && vm.list.data.items.length > 0 && <Box component="section" aria-labelledby="picker-title"><Stack direction="row" justifyContent="space-between" alignItems="baseline" gap={2}><SectionHeading id="picker-title" eyebrow="Auswahl" title="Zwei bis vier Aktivitäten." /><Chip label={`${vm.selected.length} von 4 gewählt`} /></Stack><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2,minmax(0,1fr))' }, gap: 1.5, mt: 3 }}>{vm.list.data.items.map((activity) => { const selected = vm.selected.includes(activity.id); return <Card key={activity.id} sx={{ bgcolor: selected ? 'rgba(101,200,193,.07)' : 'var(--avento-minimal-surface-subtle)' }}><ButtonBase onClick={() => vm.toggle(activity)} aria-pressed={selected} aria-label={`${activity.title} ${selected ? 'aus Vergleich entfernen' : 'zum Vergleich hinzufügen'}`} sx={{ width: '100%', textAlign: 'left', p: 2.5, justifyContent: 'stretch' }}><Stack direction="row" justifyContent="space-between" gap={2} width="100%"><Box minWidth={0}><Typography variant="h4" sx={{ overflowWrap: 'anywhere' }}>{activity.title}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .75 }}>{formatDate(activity.started_at)} · {formatDistance(activity.distance_m)} · {formatDuration(activity.moving_time_s)}</Typography></Box><Box sx={{ width: 28, height: 28, border: '1px solid', borderColor: selected ? 'primary.main' : 'divider', bgcolor: selected ? 'primary.main' : 'transparent', color: selected ? 'primary.contrastText' : 'transparent', borderRadius: 1.5, display: 'grid', placeItems: 'center', flex: 'none' }}>{selected && <CheckRoundedIcon fontSize="small" />}</Box></Stack></ButtonBase></Card> })}</Box>{vm.selected.length < 2 && <Alert severity="info" sx={{ mt: 2 }}>Wähle noch {2 - vm.selected.length} {vm.selected.length === 1 ? 'Aktivität' : 'Aktivitäten'}, um den Vergleich zu starten.</Alert>}{vm.selected.length === 4 && <Alert severity="info" sx={{ mt: 2 }}>Vier Aktivitäten sind ausgewählt. Entferne eine, bevor du eine andere hinzufügst.</Alert>}</Box>}
    {vm.compare.isPending && <Stack spacing={2}><Skeleton variant="rounded" height={180} /><Skeleton variant="rounded" height={360} /></Stack>}
    {vm.compare.isError && <Alert severity="error">Der Vergleich konnte nicht geladen werden. Ändere die Auswahl oder versuche es erneut.</Alert>}
    {result.length > 0 && <>
      <Card component="section" aria-labelledby="insight-title" sx={{ bgcolor: 'var(--avento-minimal-surface-raised)' }}><CardContent sx={{ p: { xs: 3, md: 4 } }}><Stack direction="row" gap={1} alignItems="center"><CompareArrowsRoundedIcon color="primary" /><Typography id="insight-title" variant="h2">Avento Insight</Typography></Stack><Box sx={{ mt: 2 }}><MarkdownText content={vm.compare.data?.ai_summary || 'Die Aktivitäten wurden datenbasiert gegenübergestellt. Für eine zusätzliche KI-Einordnung muss ein Anbieter konfiguriert sein.'} /></Box>{vm.compare.data?.ai_provider && <Chip label={vm.compare.data.ai_provider} variant="outlined" size="small" sx={{ mt: 2 }} />}</CardContent></Card>
      <Box component="section" aria-labelledby="leaders-title"><SectionHeading id="leaders-title" eyebrow="Schnelle Einordnung" title="Wer liegt in welcher Kennzahl vorn?" /><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3,minmax(0,1fr))' }, gap: 1.5, mt: 3 }}>{[[leaders.speed, 'Höchstes Tempo', leaders.speed ? formatSpeedMps(leaders.speed.avg_speed_mps) : 'Keine Tempodaten'], [leaders.efficiency, 'Beste Puls-Effizienz', leaders.efficiency ? efficiency(leaders.efficiency.efficiency_kmh_per_bpm) : 'Keine Pulsdaten'], [leaders.score, 'Stärkster Gesamtscore', leaders.score ? score(leaders.score.relative_score) : 'Kein Score verfügbar']].map(([leader, label, value]) => <Card key={String(label)} sx={{ bgcolor: 'var(--avento-minimal-surface-subtle)' }}><CardContent sx={{ p: 3 }}><Typography variant="overline" color="primary.main">{label as string}</Typography><Typography variant="h3" sx={{ mt: 1 }}>{(leader as ActivityComparisonMetric | undefined)?.title ?? 'Nicht bestimmbar'}</Typography><Typography color="text.secondary" sx={{ mt: .75 }}>{value as string}</Typography></CardContent></Card>)}</Box></Box>
      {profileData.length ? <ChartPanel title="Normalisierter Verlauf" description="Alle Strecken werden gemeinsam von 0 bis 100 Prozent dargestellt. So bleiben die Skalen direkt vergleichbar." summary={`Dargestellt wird ${profileMetricConfig[profileMetric].label} in ${profileMetricConfig[profileMetric].unit}. Linienmuster und Legende unterscheiden die Aktivitäten zusätzlich zur Farbe.`}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="flex-end" sx={{ mb: 2 }}><ToggleButtonGroup exclusive size="small" value={profileMetric} onChange={(_, value: ProfileMetric | null) => value && setProfileMetric(value)} aria-label="Vergleichskennzahl">{Object.entries(profileMetricConfig).map(([value, config]) => <ToggleButton key={value} value={value}>{config.label}</ToggleButton>)}</ToggleButtonGroup></Stack><ResponsiveContainer width="100%" height={350}><LineChart data={profileData} margin={{ top: 10, right: 8, left: -8, bottom: 0 }}><CartesianGrid vertical={false} stroke="rgba(255,255,255,.1)" strokeDasharray="4 4" /><XAxis type="number" dataKey="progress" domain={[0, 100]} unit=" %" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis width={58} unit={` ${profileMetricConfig[profileMetric].unit}`} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} labelFormatter={(value) => `${Number(value).toLocaleString('de-DE')} % der Strecke`} formatter={(value, name) => [formatChartValue(value, profileMetric === 'heart_rate_bpm' ? 0 : 1), name]} /><Legend />{profiles.map((profile, index) => <Line key={profile.activity_id} dataKey={`activity_${index}`} name={`${index + 1}. ${profile.title}`} stroke={colors[index]} strokeDasharray={dash[index]} strokeWidth={2.5} dot={false} connectNulls isAnimationActive={false} />)}</LineChart></ResponsiveContainer></ChartPanel> : <EmptyState title="Keine Verlaufsdaten" description="Die ausgewählten Aktivitäten besitzen keine gemeinsam vergleichbaren Trackdaten." />}
      <Box component="section" aria-labelledby="all-metrics"><SectionHeading id="all-metrics" eyebrow="Kennzahlen" title="Jede Aktivität im Detail." description="Auf kleinen Bildschirmen bleiben die Werte als Karten lesbar; es entsteht keine überbreite Tabelle." /><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: 'repeat(2,minmax(0,1fr))' }, gap: 1.5, mt: 3 }}>{metrics.map((item, index) => <Card key={item.activity_id} sx={{ bgcolor: 'var(--avento-minimal-surface-subtle)' }}><CardContent sx={{ p: 3 }}><Stack direction="row" gap={1} alignItems="center"><Typography variant="overline" color="text.secondary">{index + 1}. Aktivität</Typography><Box sx={{ width: 24, borderTop: `3px ${dash[index] ? 'dashed' : 'solid'} ${colors[index]}` }} aria-hidden="true" /></Stack><Typography variant="h3" sx={{ mt: .75, overflowWrap: 'anywhere' }}>{item.title}</Typography><Box component="dl" sx={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 2, m: 0, mt: 3 }}>{[['Distanz', formatDistance(item.distance_m)], ['Gesamtzeit', formatDuration(item.duration_s)], ['Bewegung', formatDuration(item.moving_time_s)], ['Höhe', formatElevation(item.elevation_gain_m)], ['Ø Tempo', formatSpeedMps(item.avg_speed_mps)], ['Ø / Max. Puls', `${formatHeartRate(item.avg_hr_bpm)} / ${formatHeartRate(item.max_hr_bpm)}`], ['Effizienz', efficiency(item.efficiency_kmh_per_bpm)], ['Wind', wind(item.headwind_kmh)], ['Score', score(item.relative_score)]].map(([label, value]) => <Box key={label}><Typography component="dt" variant="caption" color="text.secondary">{label}</Typography><Typography component="dd" variant="body2" fontWeight={700} sx={{ m: 0, mt: .25, overflowWrap: 'anywhere' }}>{value}</Typography></Box>)}</Box></CardContent></Card>)}</Box></Box>
    </>}
  </Stack>
}
